CREATE TABLE PERSON_AUTH (
	ID SERIAL PRIMARY KEY,
	EMAIL VARCHAR(255),
	PASSWORD VARCHAR(255),
	ROLE VARCHAR(255),
	PERSON_AUTH_USER_KEY VARCHAR(255),
	ACCOUNT_NON_EXPIRED BOOLEAN,
	ACCOUNT_NON_LOCKED BOOLEAN,
	CREDENTIALS_NON_EXPIRED BOOLEAN,
	ENABLED BOOLEAN,
	PERMISSION_ID INTEGER,
    CONSTRAINT FK_PERMISSION_AUTH FOREIGN KEY (PERMISSION_ID)
    REFERENCES PERMISSION_AUTH(ID)
);