CREATE TABLE PERSON_AUTH_PERMISSIONS (
	ID_PERSON_AUTH INTEGER NOT NULL,
	ID_PERMISSION_AUTH INTEGER NOT NULL
);

ALTER TABLE PERSON_AUTH_PERMISSIONS 
	ADD CONSTRAINT FK_PERMISSIONS FOREIGN KEY (ID_PERMISSION_AUTH) 
	REFERENCES PERMISSION_AUTH;

ALTER TABLE PERSON_AUTH_PERMISSIONS 
	ADD CONSTRAINT FK_PERSON_AUTH FOREIGN KEY (ID_PERSON_AUTH) 
	REFERENCES PERSON_AUTH;
